// Controls metadata ported from edrefcard2/www/scripts/controlsData.py
// Maps internal control key names to human-readable labels and grouping info.
// Used client-side to annotate parsed .binds data with display names.

const CONTROLS_METADATA = {
  // ── Galaxy map ──────────────────────────────────────────────────────────
  CamTranslateUp: { group: 'Galaxy Map', name: 'GalMap Up', type: 'Digital' },
  CamTranslateDown: { group: 'Galaxy Map', name: 'GalMap Down', type: 'Digital' },
  CamTranslateLeft: { group: 'Galaxy Map', name: 'GalMap Left', type: 'Digital' },
  CamTranslateRight: { group: 'Galaxy Map', name: 'GalMap Right', type: 'Digital' },
  CamTranslateForward: { group: 'Galaxy Map', name: 'GalMap Forward', type: 'Digital' },
  CamTranslateBackward: { group: 'Galaxy Map', name: 'GalMap Backward', type: 'Digital' },
  CamTranslateXAxis: { group: 'Galaxy Map', name: 'GalMap X', type: 'Analogue' },
  CamTranslateYAxis: { group: 'Galaxy Map', name: 'GalMap Y', type: 'Analogue' },
  CamTranslateZAxis: { group: 'Galaxy Map', name: 'GalMap Z', type: 'Analogue' },
  CamTranslateZHold: { group: 'Galaxy Map', name: 'GalMap Z Hold', type: 'Digital' },
  CamPitchAxis: { group: 'Galaxy Map', name: 'GalMap Pitch', type: 'Analogue' },
  CamPitchUp: { group: 'Galaxy Map', name: 'GalMap Pitch Up', type: 'Digital' },
  CamPitchDown: { group: 'Galaxy Map', name: 'GalMap Pitch Down', type: 'Digital' },
  CamYawAxis: { group: 'Galaxy Map', name: 'GalMap Yaw', type: 'Analogue' },
  CamYawLeft: { group: 'Galaxy Map', name: 'GalMap Yaw Left', type: 'Digital' },
  CamYawRight: { group: 'Galaxy Map', name: 'GalMap Yaw Right', type: 'Digital' },
  CamZoomAxis: { group: 'Galaxy Map', name: 'GalMap Zoom', type: 'Analogue' },
  CamZoomIn: { group: 'Galaxy Map', name: 'GalMap Zoom In', type: 'Digital' },
  CamZoomOut: { group: 'Galaxy Map', name: 'GalMap Zoom Out', type: 'Digital' },
  GalaxyMapHome: { group: 'Galaxy Map', name: 'GalMap Home', type: 'Digital' },

  // ── Misc (shared ship + SRV) ─────────────────────────────────────────────
  RadarRangeAxis: { group: 'Misc', name: 'Sensor Range', type: 'Analogue' },
  RadarDecreaseRange: { group: 'Misc', name: 'Dec Sensor Range', type: 'Digital' },
  RadarIncreaseRange: { group: 'Misc', name: 'Inc Sensor Range', type: 'Digital' },
  MicrophoneMute: { group: 'Misc', name: 'Microphone', type: 'Digital' },
  HMDReset: { group: 'Misc', name: 'Reset HMD', type: 'Digital' },
  OculusReset: { group: 'Misc', name: 'Reset Oculus', type: 'Digital' },
  Pause: { group: 'Misc', name: 'Main Menu', type: 'Digital' },
  FriendsMenu: { group: 'Misc', name: 'Friends', type: 'Digital' },
  NightVisionToggle: { group: 'Misc', name: 'Night Vision', type: 'Digital' },
  OpenCodexGoToDiscovery: { group: 'Misc', name: 'Codex', type: 'Digital' },
  GalnetAudio_Play_Pause: { group: 'Misc', name: 'Play/Pause Audio', type: 'Digital' },
  GalnetAudio_SkipForward: { group: 'Misc', name: 'Next Audio Track', type: 'Digital' },
  GalnetAudio_SkipBackward: { group: 'Misc', name: 'Prev Audio Track', type: 'Digital' },
  GalnetAudio_ClearQueue: { group: 'Misc', name: 'Clear Audio Queue', type: 'Digital' },

  // ── Head look ────────────────────────────────────────────────────────────
  HeadLookPitchAxis: { group: 'Head Look', name: 'Look Up/Down', type: 'Analogue' },
  HeadLookPitchAxisRaw: { group: 'Head Look', name: 'Look Up/Down (Raw)', type: 'Analogue' },
  HeadLookPitchUp: { group: 'Head Look', name: 'Look Up', type: 'Digital' },
  HeadLookPitchDown: { group: 'Head Look', name: 'Look Down', type: 'Digital' },
  HeadLookYawAxis: { group: 'Head Look', name: 'Look Left/Right', type: 'Analogue' },
  HeadLookYawAxisRaw: { group: 'Head Look', name: 'Look Left/Right (Raw)', type: 'Analogue' },
  HeadLookYawLeft: { group: 'Head Look', name: 'Look Left', type: 'Digital' },
  HeadLookYawRight: { group: 'Head Look', name: 'Look Right', type: 'Digital' },
  HeadLookReset: { group: 'Head Look', name: 'Reset Headlook', type: 'Digital' },

  // ── SRV ─────────────────────────────────────────────────────────────────
  SteeringAxis: { group: 'SRV', name: 'SRV Steer', type: 'Analogue' },
  SteerLeftButton: { group: 'SRV', name: 'Steer Left', type: 'Digital' },
  SteerRightButton: { group: 'SRV', name: 'Steer Right', type: 'Digital' },
  DriveSpeedAxis: { group: 'SRV', name: 'Speed', type: 'Analogue' },
  IncreaseSpeedButtonPartial: { group: 'SRV', name: 'Inc Speed', type: 'Digital' },
  DecreaseSpeedButtonPartial: { group: 'SRV', name: 'Dec Speed', type: 'Digital' },
  IncreaseSpeedButtonMax: { group: 'SRV', name: 'Maximum Speed', type: 'Digital' },
  DecreaseSpeedButtonMax: { group: 'SRV', name: 'Zero Speed', type: 'Digital' },
  BuggyPitchAxis: { group: 'SRV', name: 'Pitch', type: 'Analogue' },
  BuggyPitchUpButton: { group: 'SRV', name: 'Pitch Up', type: 'Digital' },
  BuggyPitchDownButton: { group: 'SRV', name: 'Pitch Down', type: 'Digital' },
  BuggyRollAxisRaw: { group: 'SRV', name: 'Roll', type: 'Analogue' },
  BuggyRollLeftButton: { group: 'SRV', name: 'Roll Left', type: 'Digital' },
  BuggyRollRightButton: { group: 'SRV', name: 'Roll Right', type: 'Digital' },
  AutoBreakBuggyButton: { group: 'SRV', name: 'Handbrake', type: 'Digital' },
  BuggyToggleReverseThrottleInput: { group: 'SRV', name: 'Reverse', type: 'Digital' },
  VerticalThrustersButton: { group: 'SRV', name: 'Vertical Thrusters', type: 'Digital' },
  ToggleDriveAssist: { group: 'SRV', name: 'Drive Assist', type: 'Digital' },
  HeadlightsBuggyButton: { group: 'SRV', name: 'Lights', type: 'Digital' },
  ToggleCargoScoop_Buggy: { group: 'SRV', name: 'Cargo Scoop', type: 'Digital' },
  RecallDismissShip: { group: 'SRV', name: 'Recall/Dismiss Ship', type: 'Digital' },
  SelectTarget_Buggy: { group: 'SRV', name: 'Target Ahead', type: 'Digital' },
  ToggleBuggyTurretButton: { group: 'SRV', name: 'Turret Mode', type: 'Digital' },
  BuggyPrimaryFireButton: { group: 'SRV', name: 'Primary Weapons', type: 'Digital' },
  BuggySecondaryFireButton: { group: 'SRV', name: 'Secondary Weapons', type: 'Digital' },
  BuggyTurretPitchAxisRaw: { group: 'SRV', name: 'Turret Pitch', type: 'Analogue' },
  BuggyTurretPitchDownButton: { group: 'SRV', name: 'Turret Down', type: 'Digital' },
  BuggyTurretPitchUpButton: { group: 'SRV', name: 'Turret Up', type: 'Digital' },
  BuggyTurretYawAxisRaw: { group: 'SRV', name: 'Turret Yaw', type: 'Analogue' },
  BuggyTurretYawLeftButton: { group: 'SRV', name: 'Turret Left', type: 'Digital' },
  BuggyTurretYawRightButton: { group: 'SRV', name: 'Turret Right', type: 'Digital' },
  BuggyCycleFireGroupNext: { group: 'SRV', name: 'Next Fire Group', type: 'Digital' },
  BuggyCycleFireGroupPrevious: { group: 'SRV', name: 'Prev Fire Group', type: 'Digital' },
  ResetPowerDistribution_Buggy: { group: 'SRV', name: 'RST Power', type: 'Digital' },
  IncreaseEnginesPower_Buggy: { group: 'SRV', name: 'ENG Power', type: 'Digital' },
  IncreaseSystemsPower_Buggy: { group: 'SRV', name: 'SYS Power', type: 'Digital' },
  IncreaseWeaponsPower_Buggy: { group: 'SRV', name: 'WEP Power', type: 'Digital' },
  GalaxyMapOpen_Buggy: { group: 'SRV', name: 'Galaxy Map', type: 'Digital' },
  SystemMapOpen_Buggy: { group: 'SRV', name: 'System Map', type: 'Digital' },
  FocusCommsPanel_Buggy: { group: 'SRV', name: 'Comms Panel', type: 'Digital' },
  FocusLeftPanel_Buggy: { group: 'SRV', name: 'Nav Panel', type: 'Digital' },
  FocusRadarPanel_Buggy: { group: 'SRV', name: 'Role Panel', type: 'Digital' },
  FocusRightPanel_Buggy: { group: 'SRV', name: 'Systems Panel', type: 'Digital' },
  QuickCommsPanel_Buggy: { group: 'SRV', name: 'Quick Comms', type: 'Digital' },
  UIFocus_Buggy: { group: 'SRV', name: 'UI Focus', type: 'Digital' },
  PlayerHUDModeToggle_Buggy: { group: 'SRV', name: 'HUD Mode', type: 'Digital' },
  EjectAllCargo_Buggy: { group: 'SRV', name: 'Eject All Cargo', type: 'Digital' },
  HeadLookToggle_Buggy: { group: 'SRV', name: 'Toggle Headlook', type: 'Digital' },
  OpenCodexGoToDiscovery_Buggy: { group: 'SRV', name: 'Codex', type: 'Digital' },

  // ── Ship — Navigation ────────────────────────────────────────────────────
  PitchAxisRaw: { group: 'Ship', name: 'Pitch', type: 'Analogue' },
  PitchUpButton: { group: 'Ship', name: 'Pitch Up', type: 'Digital' },
  PitchDownButton: { group: 'Ship', name: 'Pitch Down', type: 'Digital' },
  RollAxisRaw: { group: 'Ship', name: 'Roll', type: 'Analogue' },
  RollLeftButton: { group: 'Ship', name: 'Roll Left', type: 'Digital' },
  RollRightButton: { group: 'Ship', name: 'Roll Right', type: 'Digital' },
  YawAxisRaw: { group: 'Ship', name: 'Yaw', type: 'Analogue' },
  YawLeftButton: { group: 'Ship', name: 'Yaw Left', type: 'Digital' },
  YawRightButton: { group: 'Ship', name: 'Yaw Right', type: 'Digital' },
  YawToRollButton: { group: 'Ship', name: 'Yaw To Roll', type: 'Digital' },
  ThrottleAxis: { group: 'Ship', name: 'Throttle', type: 'Analogue' },
  SetSpeed100: { group: 'Ship', name: '100% Throttle', type: 'Digital' },
  SetSpeed75: { group: 'Ship', name: '75% Throttle', type: 'Digital' },
  SetSpeed50: { group: 'Ship', name: '50% Throttle', type: 'Digital' },
  SetSpeed25: { group: 'Ship', name: '25% Throttle', type: 'Digital' },
  SetSpeedZero: { group: 'Ship', name: 'All Stop', type: 'Digital' },
  SetSpeedMinus25: { group: 'Ship', name: '25% Reverse', type: 'Digital' },
  SetSpeedMinus50: { group: 'Ship', name: '50% Reverse', type: 'Digital' },
  SetSpeedMinus75: { group: 'Ship', name: '75% Reverse', type: 'Digital' },
  SetSpeedMinus100: { group: 'Ship', name: '100% Reverse', type: 'Digital' },
  AheadThrust: { group: 'Ship', name: 'Forward Thrust', type: 'Analogue' },
  ForwardKey: { group: 'Ship', name: 'Forward Thrust', type: 'Digital' },
  ForwardThrustButton: { group: 'Ship', name: 'Forward Thrust', type: 'Digital' },
  BackwardKey: { group: 'Ship', name: 'Reverse Thrust', type: 'Digital' },
  BackwardThrustButton: { group: 'Ship', name: 'Reverse Thrust', type: 'Digital' },
  VerticalThrustRaw: { group: 'Ship', name: 'Vertical Thrust', type: 'Analogue' },
  UpThrustButton: { group: 'Ship', name: 'Thrust Up', type: 'Digital' },
  DownThrustButton: { group: 'Ship', name: 'Thrust Down', type: 'Digital' },
  LateralThrustRaw: { group: 'Ship', name: 'Lateral Thrust', type: 'Analogue' },
  LeftThrustButton: { group: 'Ship', name: 'Thrust Left', type: 'Digital' },
  RightThrustButton: { group: 'Ship', name: 'Thrust Right', type: 'Digital' },
  ToggleReverseThrottleInput: { group: 'Ship', name: 'Reverse', type: 'Digital' },
  ToggleFlightAssist: { group: 'Ship', name: 'Flight Assist', type: 'Digital' },
  UseBoostJuice: { group: 'Ship', name: 'Boost', type: 'Digital' },
  ToggleButtonUpInput: { group: 'Ship', name: 'Silent Running', type: 'Digital' },
  ToggleCargoScoop: { group: 'Ship', name: 'Cargo Scoop', type: 'Digital' },
  ShipSpotLightToggle: { group: 'Ship', name: 'Lights', type: 'Digital' },
  UseAlternateFlightValuesToggle: { group: 'Ship', name: 'Alternate Controls', type: 'Digital' },
  PitchAxisAlternate: { group: 'Ship', name: 'Pitch (Alt)', type: 'Analogue' },
  RollAxisAlternate: { group: 'Ship', name: 'Roll (Alt)', type: 'Analogue' },
  YawAxisAlternate: { group: 'Ship', name: 'Yaw (Alt)', type: 'Analogue' },
  VerticalThrustAlternate: { group: 'Ship', name: 'Vertical Thrust (Alt)', type: 'Analogue' },
  LateralThrustAlternate: { group: 'Ship', name: 'Lateral Thrust (Alt)', type: 'Analogue' },
  GalaxyMapOpen: { group: 'Ship', name: 'Galaxy Map', type: 'Digital' },
  SystemMapOpen: { group: 'Ship', name: 'System Map', type: 'Digital' },
  HyperSuperCombination: { group: 'Ship', name: 'Hyperspace/Supercruise', type: 'Digital' },
  Hyperspace: { group: 'Ship', name: 'Hyperspace', type: 'Digital' },
  EngageSupercruise: { group: 'Ship', name: 'Supercruise', type: 'Digital' },
  Supercruise: { group: 'Ship', name: 'Supercruise', type: 'Digital' },
  TargetNextRouteSystem: { group: 'Ship', name: 'Next Jump Dest', type: 'Digital' },
  LandingGearToggle: { group: 'Ship', name: 'Landing Gear', type: 'Digital' },
  DisableRotationCorrectToggle: { group: 'Ship', name: 'Rotational Correction', type: 'Digital' },
  PitchAxis_Landing: { group: 'Ship', name: 'Pitch (Lndg)', type: 'Analogue' },
  PitchUpButton_Landing: { group: 'Ship', name: 'Pitch Up (Lndg)', type: 'Digital' },
  PitchDownButton_Landing: { group: 'Ship', name: 'Pitch Down (Lndg)', type: 'Digital' },
  RollAxis_Landing: { group: 'Ship', name: 'Roll (Lndg)', type: 'Analogue' },
  RollLeftButton_Landing: { group: 'Ship', name: 'Roll Left (Lndg)', type: 'Digital' },
  RollRightButton_Landing: { group: 'Ship', name: 'Roll Right (Lndg)', type: 'Digital' },
  YawAxis_Landing: { group: 'Ship', name: 'Yaw (Lndg)', type: 'Analogue' },
  YawLeftButton_Landing: { group: 'Ship', name: 'Yaw Left (Lndg)', type: 'Digital' },
  YawRightButton_Landing: { group: 'Ship', name: 'Yaw Right (Lndg)', type: 'Digital' },
  AheadThrust_Landing: { group: 'Ship', name: 'Forward Thrust (Lndg)', type: 'Analogue' },
  ForwardThrustButton_Landing: { group: 'Ship', name: 'Forward Thrust (Lndg)', type: 'Digital' },
  BackwardThrustButton_Landing: { group: 'Ship', name: 'Reverse Thrust (Lndg)', type: 'Digital' },
  VerticalThrust_Landing: { group: 'Ship', name: 'Vertical Thrust (Lndg)', type: 'Analogue' },
  UpThrustButton_Landing: { group: 'Ship', name: 'Thrust Up (Lndg)', type: 'Digital' },
  DownThrustButton_Landing: { group: 'Ship', name: 'Thrust Down (Lndg)', type: 'Digital' },
  LateralThrust_Landing: { group: 'Ship', name: 'Lateral Thrust (Lndg)', type: 'Analogue' },
  LeftThrustButton_Landing: { group: 'Ship', name: 'Thrust Left (Lndg)', type: 'Digital' },
  RightThrustButton_Landing: { group: 'Ship', name: 'Thrust Right (Lndg)', type: 'Digital' },

  // ── Ship — Combat ────────────────────────────────────────────────────────
  SelectTarget: { group: 'Ship', name: 'Target Ahead', type: 'Digital' },
  SelectHighestThreat: { group: 'Ship', name: 'Highest Threat', type: 'Digital' },
  CycleNextTarget: { group: 'Ship', name: 'Next Contact', type: 'Digital' },
  CyclePreviousTarget: { group: 'Ship', name: 'Prev Contact', type: 'Digital' },
  CycleNextHostileTarget: { group: 'Ship', name: 'Next Hostile', type: 'Digital' },
  CyclePreviousHostileTarget: { group: 'Ship', name: 'Prev Hostile', type: 'Digital' },
  DeployHardpointToggle: { group: 'Ship', name: 'Hardpoints', type: 'Digital' },
  PrimaryFire: { group: 'Ship', name: 'Fire 1', type: 'Digital' },
  SecondaryFire: { group: 'Ship', name: 'Fire 2', type: 'Digital' },
  CycleFireGroupNext: { group: 'Ship', name: 'Next Fire Group', type: 'Digital' },
  CycleFireGroupPrevious: { group: 'Ship', name: 'Prev Fire Group', type: 'Digital' },
  CycleNextSubsystem: { group: 'Ship', name: 'Next Subsystem', type: 'Digital' },
  CyclePreviousSubsystem: { group: 'Ship', name: 'Prev Subsystem', type: 'Digital' },
  FireChaffLauncher: { group: 'Ship', name: 'Chaff', type: 'Digital' },
  DeployHeatSink: { group: 'Ship', name: 'Heatsink', type: 'Digital' },
  UseShieldCell: { group: 'Ship', name: 'SCB', type: 'Digital' },
  ChargeECM: { group: 'Ship', name: 'ECM', type: 'Digital' },
  TriggerFieldNeutraliser: { group: 'Ship', name: 'Field Neutraliser', type: 'Digital' },
  ResetPowerDistribution: { group: 'Ship', name: 'RST Power', type: 'Digital' },
  IncreaseEnginesPower: { group: 'Ship', name: 'ENG Power', type: 'Digital' },
  IncreaseSystemsPower: { group: 'Ship', name: 'SYS Power', type: 'Digital' },
  IncreaseWeaponsPower: { group: 'Ship', name: 'WEP Power', type: 'Digital' },

  // ── Ship — Wings ─────────────────────────────────────────────────────────
  TargetWingman0: { group: 'Ship', name: 'Wingman 1', type: 'Digital' },
  TargetWingman1: { group: 'Ship', name: 'Wingman 2', type: 'Digital' },
  TargetWingman2: { group: 'Ship', name: 'Wingman 3', type: 'Digital' },
  SelectTargetsTarget: { group: 'Ship', name: "Wingman's Target", type: 'Digital' },
  WingNavLock: { group: 'Ship', name: 'Wingman Navlock', type: 'Digital' },

  // ── Ship — UI ────────────────────────────────────────────────────────────
  UIFocus: { group: 'Ship', name: 'UI Focus', type: 'Digital' },
  FocusCommsPanel: { group: 'Ship', name: 'Comms Panel', type: 'Digital' },
  QuickCommsPanel: { group: 'Ship', name: 'Quick Comms', type: 'Digital' },
  FocusLeftPanel: { group: 'Ship', name: 'Nav Panel', type: 'Digital' },
  FocusRightPanel: { group: 'Ship', name: 'Systems Panel', type: 'Digital' },
  FocusRadarPanel: { group: 'Ship', name: 'Role Panel', type: 'Digital' },
  PlayerHUDModeToggle: { group: 'Ship', name: 'HUD Mode', type: 'Digital' },

  // ── Ship — General ───────────────────────────────────────────────────────
  EjectAllCargo: { group: 'Ship', name: 'Eject All Cargo', type: 'Digital' },
  HeadLookToggle: { group: 'Ship', name: 'Toggle Headlook', type: 'Digital' },
  OrbitLinesToggle: { group: 'Ship', name: 'Orbit Lines', type: 'Digital' },
  ShowPGScoreSummaryInput: { group: 'Ship', name: 'CQC Score', type: 'Digital' },
  MouseReset: { group: 'Ship', name: 'Reset Mouse', type: 'Digital' },
  WeaponColourToggle: { group: 'Ship', name: 'Weapon Colour', type: 'Digital' },
  EngineColourToggle: { group: 'Ship', name: 'Engine Colour', type: 'Digital' },
  BlockMouseDecay: { group: 'Ship', name: 'Block Mouse Decay', type: 'Digital' },

  // ── Fighter ──────────────────────────────────────────────────────────────
  OrderRequestDock: { group: 'Fighter', name: 'Dock SLF', type: 'Digital' },
  OrderDefensiveBehaviour: { group: 'Fighter', name: 'Be Defensive', type: 'Digital' },
  OrderAggressiveBehaviour: { group: 'Fighter', name: 'Be Aggressive', type: 'Digital' },
  OrderFocusTarget: { group: 'Fighter', name: 'Attack My Target', type: 'Digital' },
  OrderHoldFire: { group: 'Fighter', name: 'Hold Fire', type: 'Digital' },
  OrderHoldPosition: { group: 'Fighter', name: 'Hold Position', type: 'Digital' },
  OrderFollow: { group: 'Fighter', name: 'Follow', type: 'Digital' },
  OpenOrders: { group: 'Fighter', name: 'Crew Orders', type: 'Digital' },

  // ── Multicrew ────────────────────────────────────────────────────────────
  MultiCrewToggleMode: { group: 'Multicrew', name: 'Multicrew Mode', type: 'Digital' },
  MultiCrewThirdPersonPitchAxisRaw: { group: 'Multicrew', name: 'Pitch', type: 'Analogue' },
  MultiCrewThirdPersonPitchUpButton: { group: 'Multicrew', name: 'Pitch Up', type: 'Digital' },
  MultiCrewThirdPersonPitchDownButton: { group: 'Multicrew', name: 'Pitch Down', type: 'Digital' },
  MultiCrewThirdPersonYawAxisRaw: { group: 'Multicrew', name: 'Yaw', type: 'Analogue' },
  MultiCrewThirdPersonYawLeftButton: { group: 'Multicrew', name: 'Yaw Left', type: 'Digital' },
  MultiCrewThirdPersonYawRightButton: { group: 'Multicrew', name: 'Yaw Right', type: 'Digital' },
  MultiCrewThirdPersonFovAxisRaw: { group: 'Multicrew', name: 'Field of View', type: 'Analogue' },
  MultiCrewThirdPersonFovOutButton: { group: 'Multicrew', name: 'Field of View Out', type: 'Digital' },
  MultiCrewThirdPersonFovInButton: { group: 'Multicrew', name: 'Field of View In', type: 'Digital' },
  MultiCrewPrimaryFire: { group: 'Multicrew', name: 'Fire 1', type: 'Digital' },
  MultiCrewSecondaryFire: { group: 'Multicrew', name: 'Fire 2', type: 'Digital' },
  MultiCrewPrimaryUtilityFire: { group: 'Multicrew', name: 'Primary Utility', type: 'Digital' },
  MultiCrewSecondaryUtilityFire: { group: 'Multicrew', name: 'Secondary Utility', type: 'Digital' },
  MultiCrewCockpitUICycleForward: { group: 'Multicrew', name: 'UI Forward', type: 'Digital' },
  MultiCrewCockpitUICycleBackward: { group: 'Multicrew', name: 'UI Backward', type: 'Digital' },

  // ── Scanners ─────────────────────────────────────────────────────────────
  ExplorationFSSEnter: { group: 'Scanners', name: 'Enter FSS', type: 'Digital' },
  ExplorationFSSCameraPitch: { group: 'Scanners', name: 'FSS Pitch', type: 'Analogue' },
  ExplorationFSSCameraPitchIncreaseButton: { group: 'Scanners', name: 'FSS Pitch Up', type: 'Digital' },
  ExplorationFSSCameraPitchDecreaseButton: { group: 'Scanners', name: 'FSS Pitch Down', type: 'Digital' },
  ExplorationFSSCameraYaw: { group: 'Scanners', name: 'FSS Yaw', type: 'Analogue' },
  ExplorationFSSCameraYawIncreaseButton: { group: 'Scanners', name: 'FSS Yaw Right', type: 'Digital' },
  ExplorationFSSCameraYawDecreaseButton: { group: 'Scanners', name: 'FSS Yaw Left', type: 'Digital' },
  ExplorationFSSZoomIn: { group: 'Scanners', name: 'Zoom FSS In', type: 'Digital' },
  ExplorationFSSZoomOut: { group: 'Scanners', name: 'Zoom FSS Out', type: 'Digital' },
  ExplorationFSSMiniZoomIn: { group: 'Scanners', name: 'Step Zoom FSS In', type: 'Digital' },
  ExplorationFSSMiniZoomOut: { group: 'Scanners', name: 'Step Zoom FSS Out', type: 'Digital' },
  ExplorationFSSRadioTuningX_Raw: { group: 'Scanners', name: 'FSS Tuning', type: 'Analogue' },
  ExplorationFSSRadioTuningX_Increase: { group: 'Scanners', name: 'FSS Tune Right', type: 'Digital' },
  ExplorationFSSRadioTuningX_Decrease: { group: 'Scanners', name: 'FSS Tune Left', type: 'Digital' },
  ExplorationFSSRadioTuningAbsoluteX: { group: 'Scanners', name: 'FSS Tuning (Abs)', type: 'Analogue' },
  ExplorationFSSDiscoveryScan: { group: 'Scanners', name: 'FSS Honk', type: 'Digital' },
  ExplorationFSSQuit: { group: 'Scanners', name: 'Exit FSS', type: 'Digital' },
  ExplorationFSSTarget: { group: 'Scanners', name: 'Target FSS', type: 'Digital' },
  ExplorationFSSShowHelp: { group: 'Scanners', name: 'FSS Help', type: 'Digital' },
  ExplorationSAAChangeScannedAreaViewToggle: { group: 'Scanners', name: 'Toggle Planet Front/Back', type: 'Digital' },
  ExplorationSAAExitThirdPerson: { group: 'Scanners', name: 'Exit DSS', type: 'Digital' },
  ExplorationSAANextGenus: { group: 'Scanners', name: 'Next Signal (DSS)', type: 'Digital' },
  ExplorationSAAPreviousGenus: { group: 'Scanners', name: 'Prev Signal (DSS)', type: 'Digital' },
  SAAThirdPersonPitchAxisRaw: { group: 'Scanners', name: 'Pitch (DSS)', type: 'Analogue' },
  SAAThirdPersonPitchUpButton: { group: 'Scanners', name: 'Pitch Up (DSS)', type: 'Digital' },
  SAAThirdPersonPitchDownButton: { group: 'Scanners', name: 'Pitch Down (DSS)', type: 'Digital' },
  SAAThirdPersonYawAxisRaw: { group: 'Scanners', name: 'DSS Yaw', type: 'Analogue' },
  SAAThirdPersonYawLeftButton: { group: 'Scanners', name: 'Yaw Left (DSS)', type: 'Digital' },
  SAAThirdPersonYawRightButton: { group: 'Scanners', name: 'Yaw Right (DSS)', type: 'Digital' },
  SAAThirdPersonFovAxisRaw: { group: 'Scanners', name: 'DSS Field of View', type: 'Analogue' },
  SAAThirdPersonFovOutButton: { group: 'Scanners', name: 'DSS FoV Out', type: 'Digital' },
  SAAThirdPersonFovInButton: { group: 'Scanners', name: 'DSS FoV In', type: 'Digital' },
  ExplorationSAAShowHelp: { group: 'Scanners', name: 'DSS Help', type: 'Digital' },

  // ── Camera ───────────────────────────────────────────────────────────────
  PhotoCameraToggle: { group: 'Camera', name: 'External Cam', type: 'Digital' },
  PhotoCameraToggle_Buggy: { group: 'Camera', name: 'External Cam (SRV)', type: 'Digital' },
  ToggleVanityCamera: { group: 'Camera', name: 'External Cam', type: 'Digital' },
  ToggleVanityCamera_Buggy: { group: 'Camera', name: 'External Cam (SRV)', type: 'Digital' },
  ToggleFreeCam: { group: 'Camera', name: 'Free Cam', type: 'Digital' },
  QuitCamera: { group: 'Camera', name: 'Exit Free Cam', type: 'Digital' },
  VanityCameraOne: { group: 'Camera', name: 'Cam — Cockpit Front', type: 'Digital' },
  VanityCameraTwo: { group: 'Camera', name: 'Cam — Cockpit Back', type: 'Digital' },
  VanityCameraThree: { group: 'Camera', name: 'Cam — Commander 1', type: 'Digital' },
  VanityCameraFour: { group: 'Camera', name: 'Cam — Commander 2', type: 'Digital' },
  VanityCameraFive: { group: 'Camera', name: 'Cam — Co-Pilot 1', type: 'Digital' },
  VanityCameraSix: { group: 'Camera', name: 'Cam — Co-Pilot 2', type: 'Digital' },
  VanityCameraSeven: { group: 'Camera', name: 'Cam — Front', type: 'Digital' },
  VanityCameraEight: { group: 'Camera', name: 'Cam — Back', type: 'Digital' },
  VanityCameraNine: { group: 'Camera', name: 'Cam — Low', type: 'Digital' },
  VanityCameraTen: { group: 'Camera', name: 'Cam — Back Low', type: 'Digital' },
  VanityCameraScrollRight: { group: 'Camera', name: 'Next Cam', type: 'Digital' },
  VanityCameraScrollLeft: { group: 'Camera', name: 'Prev Cam', type: 'Digital' },
  FreeCamToggleHUD: { group: 'Camera', name: 'Toggle HUD', type: 'Digital' },
  FreeCamSpeedInc: { group: 'Camera', name: 'Inc Cam Speed', type: 'Digital' },
  FreeCamSpeedDec: { group: 'Camera', name: 'Dec Cam Speed', type: 'Digital' },
  FreeCamZoomIn: { group: 'Camera', name: 'Zoom In', type: 'Digital' },
  FreeCamZoomOut: { group: 'Camera', name: 'Zoom Out', type: 'Digital' },
  MoveFreeCamX: { group: 'Camera', name: 'Cam X', type: 'Analogue' },
  MoveFreeCamLeft: { group: 'Camera', name: 'Cam Left', type: 'Digital' },
  MoveFreeCamRight: { group: 'Camera', name: 'Cam Right', type: 'Digital' },
  MoveFreeCamY: { group: 'Camera', name: 'Cam Y', type: 'Analogue' },
  MoveFreeCamUp: { group: 'Camera', name: 'Cam Up', type: 'Digital' },
  MoveFreeCamDown: { group: 'Camera', name: 'Cam Down', type: 'Digital' },
  MoveFreeCamZ: { group: 'Camera', name: 'Cam Z', type: 'Analogue' },
  MoveFreeCamForward: { group: 'Camera', name: 'Cam Forwards', type: 'Digital' },
  MoveFreeCamBackwards: { group: 'Camera', name: 'Cam Backwards', type: 'Digital' },
  MoveFreeCamUpAxis: { group: 'Camera', name: 'Cam Up Axis', type: 'Analogue' },
  MoveFreeCamDownAxis: { group: 'Camera', name: 'Cam Down Axis', type: 'Analogue' },
  PitchCamera: { group: 'Camera', name: 'Cam Pitch', type: 'Analogue' },
  PitchCameraUp: { group: 'Camera', name: 'Cam Pitch Up', type: 'Digital' },
  PitchCameraDown: { group: 'Camera', name: 'Cam Pitch Down', type: 'Digital' },
  RollCamera: { group: 'Camera', name: 'Cam Roll', type: 'Analogue' },
  RollCameraLeft: { group: 'Camera', name: 'Cam Roll Left', type: 'Digital' },
  RollCameraRight: { group: 'Camera', name: 'Cam Roll Right', type: 'Digital' },
  YawCamera: { group: 'Camera', name: 'Cam Yaw', type: 'Analogue' },
  YawCameraLeft: { group: 'Camera', name: 'Cam Yaw Left', type: 'Digital' },
  YawCameraRight: { group: 'Camera', name: 'Cam Yaw Right', type: 'Digital' },
  ToggleRotationLock: { group: 'Camera', name: 'Cam Rotation Lock', type: 'Digital' },
  ToggleReverseThrottleInputFreeCam: { group: 'Camera', name: 'Cam Reverse', type: 'Digital' },
  FixCameraRelativeToggle: { group: 'Camera', name: 'Lock to Vehicle', type: 'Digital' },
  FixCameraWorldToggle: { group: 'Camera', name: 'Lock to World', type: 'Digital' },
  ToggleAdvanceMode: { group: 'Camera', name: 'Advanced Cam', type: 'Digital' },
  FStopInc: { group: 'Camera', name: 'Inc Blur', type: 'Digital' },
  FStopDec: { group: 'Camera', name: 'Dec Blur', type: 'Digital' },
  FocusDistanceInc: { group: 'Camera', name: 'Focus Further', type: 'Digital' },
  FocusDistanceDec: { group: 'Camera', name: 'Focus Nearer', type: 'Digital' },
  StoreEnableRotation: { group: 'Camera', name: 'Store Cam Rotation', type: 'Digital' },
  StorePitchCamera: { group: 'Camera', name: 'Store Cam Pitch', type: 'Analogue' },
  StorePitchCameraUp: { group: 'Camera', name: 'Store Cam Pitch Up', type: 'Digital' },
  StorePitchCameraDown: { group: 'Camera', name: 'Store Cam Pitch Down', type: 'Digital' },
  StoreYawCamera: { group: 'Camera', name: 'Store Cam Yaw', type: 'Analogue' },
  StoreYawCameraLeft: { group: 'Camera', name: 'Store Cam Yaw Left', type: 'Digital' },
  StoreYawCameraRight: { group: 'Camera', name: 'Store Cam Yaw Right', type: 'Digital' },
  StoreCamZoomIn: { group: 'Camera', name: 'Store Cam Zoom In', type: 'Digital' },
  StoreCamZoomOut: { group: 'Camera', name: 'Store Cam Zoom Out', type: 'Digital' },
  StoreToggle: { group: 'Camera', name: 'Store Toggle Preview', type: 'Digital' },

  // ── Panel UI ─────────────────────────────────────────────────────────────
  UI_Up: { group: 'UI', name: 'UI Up', type: 'Digital' },
  UI_Down: { group: 'UI', name: 'UI Down', type: 'Digital' },
  UI_Left: { group: 'UI', name: 'UI Left', type: 'Digital' },
  UI_Right: { group: 'UI', name: 'UI Right', type: 'Digital' },
  UI_Select: { group: 'UI', name: 'UI Select', type: 'Digital' },
  UI_Back: { group: 'UI', name: 'UI Back', type: 'Digital' },
  UI_Toggle: { group: 'UI', name: 'UI Toggle', type: 'Digital' },
  CycleNextPanel: { group: 'UI', name: 'Next Panel', type: 'Digital' },
  CyclePreviousPanel: { group: 'UI', name: 'Prev Panel', type: 'Digital' },
  CycleNextPage: { group: 'UI', name: 'Next Page', type: 'Digital' },
  CyclePreviousPage: { group: 'UI', name: 'Prev Page', type: 'Digital' },

  // ── Holo-Me ──────────────────────────────────────────────────────────────
  CommanderCreator_Undo: { group: 'Holo-Me', name: 'Undo Holo-Me', type: 'Digital' },
  CommanderCreator_Redo: { group: 'Holo-Me', name: 'Redo Holo-Me', type: 'Digital' },
  CommanderCreator_Rotation_MouseToggle: { group: 'Holo-Me', name: 'Toggle Holo-Me Rotation', type: 'Digital' },
  CommanderCreator_Rotation: { group: 'Holo-Me', name: 'Rotate Holo-Me', type: 'Digital' },

  // ── On Foot — Navigation ─────────────────────────────────────────────────
  HumanoidForwardAxis: { group: 'On Foot', name: 'Fwd/Back', type: 'Analogue' },
  HumanoidForwardButton: { group: 'On Foot', name: 'Fwd', type: 'Digital' },
  HumanoidBackwardButton: { group: 'On Foot', name: 'Back', type: 'Digital' },
  HumanoidPitchAxis: { group: 'On Foot', name: 'Pitch', type: 'Analogue' },
  HumanoidPitchUpButton: { group: 'On Foot', name: 'Pitch Up', type: 'Digital' },
  HumanoidPitchDownButton: { group: 'On Foot', name: 'Pitch Down', type: 'Digital' },
  HumanoidStrafeAxis: { group: 'On Foot', name: 'Strafe', type: 'Analogue' },
  HumanoidStrafeLeftButton: { group: 'On Foot', name: 'Strafe Left', type: 'Digital' },
  HumanoidStrafeRightButton: { group: 'On Foot', name: 'Strafe Right', type: 'Digital' },
  HumanoidRotateAxis: { group: 'On Foot', name: 'Turn', type: 'Analogue' },
  HumanoidRotateLeftButton: { group: 'On Foot', name: 'Turn Left', type: 'Digital' },
  HumanoidRotateRightButton: { group: 'On Foot', name: 'Turn Right', type: 'Digital' },
  GalaxyMapOpen_Humanoid: { group: 'On Foot', name: 'Galaxy Map', type: 'Digital' },
  SystemMapOpen_Humanoid: { group: 'On Foot', name: 'System Map', type: 'Digital' },

  // ── On Foot — Combat ─────────────────────────────────────────────────────
  HumanoidPrimaryFireButton: { group: 'On Foot', name: 'Fire', type: 'Digital' },
  HumanoidActivateSuitAbilityButton: { group: 'On Foot', name: 'Suit Ability', type: 'Digital' },
  HumanoidConflictContextualUIButton: { group: 'On Foot', name: 'Combat UI', type: 'Digital' },
  HumanoidCrouchButton: { group: 'On Foot', name: 'Crouch', type: 'Digital' },
  HumanoidHideWeaponButton: { group: 'On Foot', name: 'Holster', type: 'Digital' },
  HumanoidJumpButton: { group: 'On Foot', name: 'Jump', type: 'Digital' },
  HumanoidMeleeButton: { group: 'On Foot', name: 'Melee', type: 'Digital' },
  HumanoidOpenAccessPanelButton: { group: 'On Foot', name: 'Open Access Panel', type: 'Digital' },
  HumanoidPrimaryInteractButton: { group: 'On Foot', name: 'Interact', type: 'Digital' },
  HumanoidPulseScanButton: { group: 'On Foot', name: 'Pulse Scan', type: 'Digital' },
  HumanoidReloadButton: { group: 'On Foot', name: 'Reload', type: 'Digital' },
  HumanoidSecondaryInteractButton: { group: 'On Foot', name: 'Interact 2', type: 'Digital' },
  HumanoidSelectNextGrenadeTypeButton: { group: 'On Foot', name: 'Next Grenade', type: 'Digital' },
  HumanoidSelectNextWeaponButton: { group: 'On Foot', name: 'Next Weapon', type: 'Digital' },
  HumanoidSelectPreviousGrenadeTypeButton: { group: 'On Foot', name: 'Prev Grenade', type: 'Digital' },
  HumanoidSelectPreviousWeaponButton: { group: 'On Foot', name: 'Prev Weapon', type: 'Digital' },
  HumanoidSelectPrimaryWeaponButton: { group: 'On Foot', name: 'Weapon 1', type: 'Digital' },
  HumanoidSelectSecondaryWeaponButton: { group: 'On Foot', name: 'Weapon 2', type: 'Digital' },
  HumanoidSelectUtilityWeaponButton: { group: 'On Foot', name: 'Select Utility', type: 'Digital' },
  HumanoidSprintButton: { group: 'On Foot', name: 'Sprint', type: 'Digital' },
  HumanoidSwitchToCompAnalyser: { group: 'On Foot', name: 'Comp Analyser', type: 'Digital' },
  HumanoidSwitchToRechargeTool: { group: 'On Foot', name: 'Recharge Tool', type: 'Digital' },
  HumanoidSwitchToSuitTool: { group: 'On Foot', name: 'Suit Tool', type: 'Digital' },
  HumanoidSwitchWeapon: { group: 'On Foot', name: 'Switch Weapon', type: 'Digital' },
  HumanoidThrowGrenadeButton: { group: 'On Foot', name: 'Throw Grenade', type: 'Digital' },
  HumanoidToggleFlashlightButton: { group: 'On Foot', name: 'Flashlight', type: 'Digital' },
  HumanoidToggleJumpAssistModuleButton: { group: 'On Foot', name: 'Jump Assist', type: 'Digital' },
  HumanoidToggleMissionHelpPanelButton: { group: 'On Foot', name: 'Mission Help', type: 'Digital' },
  HumanoidToggleNightVisionButton: { group: 'On Foot', name: 'Night Vision', type: 'Digital' },
  HumanoidToggleShieldBoosterModuleButton: { group: 'On Foot', name: 'Shield Boost', type: 'Digital' },
  HumanoidToggleShieldsButton: { group: 'On Foot', name: 'Shields', type: 'Digital' },
  HumanoidToggleToolModeButton: { group: 'On Foot', name: 'Tool Mode', type: 'Digital' },
  HumanoidToggleWeaponBoosterModuleButton: { group: 'On Foot', name: 'Weapon Booster', type: 'Digital' },
  HumanoidZoomButton: { group: 'On Foot', name: 'Zoom', type: 'Digital' },
  HumanoidWalkButton: { group: 'On Foot', name: 'Walk', type: 'Digital' },
  HumanoidHealthPack: { group: 'On Foot', name: 'Health Pack', type: 'Digital' },
  HumanoidBattery: { group: 'On Foot', name: 'Battery Pack', type: 'Digital' },
  HumanoidSelectFragGrenade: { group: 'On Foot', name: 'Frag Grenade', type: 'Digital' },
  HumanoidSelectShieldGrenade: { group: 'On Foot', name: 'Shield Grenade', type: 'Digital' },
  HumanoidSelectEMPGrenade: { group: 'On Foot', name: 'EMP Grenade', type: 'Digital' },
  HumanoidClearAuthorityLevel: { group: 'On Foot', name: 'Clear Auth Level', type: 'Digital' },
  HumanoidResetPowerDistributionButton: { group: 'On Foot', name: 'RST Power', type: 'Digital' },
  HumanoidIncreaseEnginesPowerButton: { group: 'On Foot', name: 'ENG Power', type: 'Digital' },
  HumanoidIncreaseSystemsPowerButton: { group: 'On Foot', name: 'SYS Power', type: 'Digital' },
  HumanoidIncreaseWeaponsPowerButton: { group: 'On Foot', name: 'WEP Power', type: 'Digital' },
  FocusCommsPanel_Humanoid: { group: 'On Foot', name: 'Comms Panel', type: 'Digital' },
  QuickCommsPanel_Humanoid: { group: 'On Foot', name: 'Quick Comms', type: 'Digital' },
  HumanoidItemWheelButton: { group: 'On Foot', name: 'Item Wheel', type: 'Digital' },
  HumanoidItemWheelButton_XAxis: { group: 'On Foot', name: 'Item L/R', type: 'Analogue' },
  HumanoidItemWheelButton_XLeft: { group: 'On Foot', name: 'Item Left', type: 'Digital' },
  HumanoidItemWheelButton_XRight: { group: 'On Foot', name: 'Item Right', type: 'Digital' },
  HumanoidItemWheelButton_YAxis: { group: 'On Foot', name: 'Item Up/Down', type: 'Analogue' },
  HumanoidItemWheelButton_YDown: { group: 'On Foot', name: 'Item Down', type: 'Digital' },
  HumanoidItemWheelButton_YUp: { group: 'On Foot', name: 'Item Up', type: 'Digital' },
  HumanoidEmoteWheelButton: { group: 'On Foot', name: 'Emote Wheel', type: 'Digital' },
  HumanoidUtilityWheelCycleMode: { group: 'On Foot', name: 'Utility Wheel', type: 'Digital' },
  HumanoidEmoteSlot1: { group: 'On Foot', name: 'Emote 1', type: 'Digital' },
  HumanoidEmoteSlot2: { group: 'On Foot', name: 'Emote 2', type: 'Digital' },
  HumanoidEmoteSlot3: { group: 'On Foot', name: 'Emote 3', type: 'Digital' },
  HumanoidEmoteSlot4: { group: 'On Foot', name: 'Emote 4', type: 'Digital' },
  HumanoidEmoteSlot5: { group: 'On Foot', name: 'Emote 5', type: 'Digital' },
  HumanoidEmoteSlot6: { group: 'On Foot', name: 'Emote 6', type: 'Digital' },
  HumanoidEmoteSlot7: { group: 'On Foot', name: 'Emote 7', type: 'Digital' },
  HumanoidEmoteSlot8: { group: 'On Foot', name: 'Emote 8', type: 'Digital' },
  PhotoCameraToggle_Humanoid: { group: 'Camera', name: 'External Cam (On Foot)', type: 'Digital' }
}

export default CONTROLS_METADATA
